### ISSUE TITLE
[FEATURE] Support for Arguments in Commandline

### ISSUE THREAD

**Issue by ArchooD2** [ArchooD2/KevinBacon#1]
Description:
I think that adding support for command-line arguments would enhance the functionality and usability of the KevinBacon project. This feature will allow users to specify input parameters directly through the command line, making the tool more flexible and user-friendly.

maybe all be optional, but currently the ones I can think of are "start_article" as -s or --source, "end_article" as -t or --target, and "depth" as -d or --depth maybe?

**Comment by ErascusPlatypus** [comment]
Hi! I've modified the code to add in the command line arguments. I've submitted a pull request. Please check it out.......

**Comment by ArchooD2** [comment]
Merged! Thanks ErascusPlatypus!
