### ISSUE TITLE
Local Cache Saves

### ISSUE THREAD

**Issue by ArchooD2** [ArchooD2/KevinBacon#10]

**Comment by ArchooD2** [comment]
I should've set this as a description:

I want it to be able to save which things go where as a json or something, implement it however you want, but make sure that it doesn't make it slower on average, repeat runs being faster is the priority!

**Comment by MuddyHope** [comment]
Could you elaborate on what needs to be json? As this description for an issue doesn't give a whole picture.

**Comment by ArchooD2** [comment]
I.e. save connected links that are found in a json or other file that you want, so that you don't have to query wikipedia's api for the same stuff twice. From what I can remember, that's a good way to cut costs if I want to make this into a website later

Sorry this took me a week to reply, kinda busy at the moment.

**Comment by MuddyHope** [comment]
@ArchooD2 
I will be working on this, will be saving it in a json file so, it is easily findable without overhead calls again. 
**Example**: 
search params -> _text1, _text2, _depth

In json, it will be saved as 
`{_text1.lower() - _text2.lower(): "yes", ...}`
